name: week7_institute_project_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  external_path: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.15
  flutter_email_sender: ^5.0.2
  image_picker: ^1.1.2
  pdf: ^3.3.0
  printing: ^5.6.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  syncfusion_flutter_charts: ^20.2.44
  excel: ^2.0.5
  path_provider: ^2.0.11
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  assets:
    - assets/Younus_1.jpg
    - assets/iat_logo.jpg
    - assets/NTEM.png

